### PR TITLE
Added RoboTablets to dxmProducts

### PR DESCRIPTION
**Pull request by AcidicNic**
RoboTablets (r30) is a popular and fairly new product [that only contains freebase DXM](https://www.reddit.com/r/dxm/comments/jcds6h/we_need_a_discussion_about_the_new_robotablets/). Because it's entirely freebase dxm, people overestimate their doses thinking it's like dxm HBr. It deserves a spot on the calculator!

### CODE REVIEW

**Comment by yoisahb5** [comment]
The math seems wrong though. The molecular weight of HBr and freebase are 370.3 and 271.4 respectively, coming out to a magnifying factor of 1.3644 which makes a 30mg freebase tablet equivalent to a 40.9322mg HBr one.

https://www.reddit.com/r/dxm/comments/ibdssx/robotablet_information/
https://pubchem.ncbi.nlm.nih.gov/compound/Dextromethorphan
https://pubchem.ncbi.nlm.nih.gov/compound/Dextromethorphan-hydrobromide-monohydrate

**Comment by LunaUrsa** [comment]
Im happy to update this, just want to make sure i have the math right, from that reddit thread:

"To convert an HBr dose to freebase, divide the HBr dose by 1.37."

**Comment by yoisahb5** [comment]
Sure, that's pretty close to the 1.3644 mentioned previously. 40.9322mg HBR divided by 1.37 is 29.8775mg.

**Comment by LunaUrsa** [comment]
I've updated the PR and pushed the changes, thanks all

**Pull request merged**
